name: Validate JIRA Automation Coverage

on:
  workflow_dispatch:
    inputs:
      fix_version_link:
        description: 'JIRA Fix Version ID'
        required: true
        type: string
  # push:
  #   branches:
  #     - '**'   # Triggers on any branch

jobs:
  validate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf ~/.cache
          df -h

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set API Key as Environment Variable
        run: echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install requests
          pip install jira  # JIRA Python library
          pip install --upgrade openai

      - name: Extract JIRA issues for Fix Version
        id: get_jira_issues
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: "https://shalinithilakan.atlassian.net"
        run: |
          JIRA_API_URL="https://shalinithilakan.atlassian.net/rest/api/2/search?jql=fixVersion=${{ github.event.inputs.fix_version_link }}"
          RESPONSE=$(curl -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" -X GET -H "Content-Type: application/json" "$JIRA_API_URL")
          # ISSUES=$(echo "$RESPONSE" | jq -r '.issues' | tr '\n' ' ' | sed 's/"/\\"/g') 
          ISSUES=$(echo "$RESPONSE" | jq -r '.issues') 

          #ISSUES=$(echo "$RESPONSE" | tr '\n' ' ' | sed 's/"/\\"/g') 

          if [[ -z "$ISSUES" || "$ISSUES" == "null" ]]; then
            echo "❌ No issues found in JIRA fix version."
            exit 1
          fi

          echo "✅ Fetched Issues"
          echo "$ISSUES"

          JSON_LIST=$(echo "$ISSUES" | jq -c '[.[] | .id]')
          echo "✅ Fetched ISSUE List"
          echo "$JSON_LIST"

          echo "ISSUE_LIST=$JSON_LIST" >> $GITHUB_ENV

          #AC=$(echo "$ISSUES" | jq -c 'reduce .[] as $item ({}; .[$item.key] = $item.fields.description)')

          

          #echo "$AC" > criteria.json
          
          # # Save the full JSON response to a file
          #echo "$ISSUES" > jira_issues.json

          # Store in GitHub Actions Environment Variable safely
          # echo "ISSUES<<EOF" >> $GITHUB_ENV
          # echo "$ISSUES" >> $GITHUB_ENV
          # echo "EOF" >> $GITHUB_ENV

      - name: Fetch JIRA Acceptance Criteria
        id: fetch_jira
        run: |
          AC_LIST='[]'
          for issue in $(echo "$ISSUE_LIST" | jq -r '.[]'); do
            echo "Fetching JIRA issue: $issue"

            JIRA_API_URL="https://shalinithilakan.atlassian.net/rest/api/3/issue/$issue"
            RESPONSE=$(curl -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" -X GET -H "Content-Type: application/json" "$JIRA_API_URL")
            #ACCEPTANCE_CRITERIA=$(echo "$RESPONSE" | jq -r '.fields.description.content') # Replace with actual field ID
            # Extract acceptance criteria safely
            ACCEPTANCE_CRITERIA=$(echo "$RESPONSE" | jq -c '.fields.description.content // ""') # Replace with actual field ID

            # Extract & Decode JSON-Stringified Acceptance Criteria
            #ACCEPTANCE_CRITERIA=$(echo "$RESPONSE" | jq -r '.fields.description.content // ""' | jq -c 'fromjson')

            # # Append to JSON list
            #AC_LIST=$(echo "$AC_LIST" | jq --arg desc "$ACCEPTANCE_CRITERIA" '. + [$desc]')

            # Append to JSON array
            AC_LIST=$(echo "$AC_LIST" | jq --argjson desc "$ACCEPTANCE_CRITERIA" '. + [$desc]')
          done

          echo "✅ Fetched Acceptance Criteria."
          echo "$AC_LIST"

          # Ensure JSON is correctly formatted
          echo "$AC_LIST" | jq '.' > criteria.json

          # Flatten the nested lists and extract only "text" values
          # PLAIN_JSON_LIST=$(jq '[.[]
          #   | .[]
          #   | .content[]
          #   | select(.text != null)
          #   | .text
          # ]' $AC_LIST)

          # echo "Final JSON List: $PLAIN_JSON_LIST"
          # echo "CRITERIA=$PLAIN_JSON_LIST" >> $GITHUB_ENV

          # CRITERIA='[]'
          # for ac in $(echo "$AC_LIST" | jq -r '.[]'); do
          #   # Extract all "text" values from "content" and join them into a single string
          #   TEXT_STRING=$(echo "$ac" | jq -r '[.[] | .content[]? | .text] | join(" ")')
            
          #   # Append to JSON list
          #   CRITERIA=$(echo "$CRITERIA" | jq --argjson desc "$TEXT_STRING" '. + [$desc]')
          # done

          # echo "✅ Extracted Acceptance Criteria."
          # echo "$CRITERIA"

          # echo "$CRITERIA" | jq '.' > criteria.json

      # - name: Extract acceptance criteria
      #   id: extract_criteria
      #   run: |
      #     # python scripts/extract_acceptance_criteria.py > criteria.json
      #     python scripts/extract_acceptance_criteria.py jira_issues.json > criteria.json         

      - name: Search for Feature Files and Step Definitions
        id: fetch_tests
        run: |
          FEATURE_FILES=$(find ./src/test/resources/features -name "*.feature")
          STEP_DEF_FILES=$(find ./src/test/java/stepdefinitions -name "*.java")

          if [[ -z "$FEATURE_FILES" || -z "$STEP_DEF_FILES" ]]; then
            echo "❌ No test automation files found."
            exit 1
          fi

          echo "✅ Found Feature Files:"
          echo "$FEATURE_FILES"
          echo "✅ Found Step Definitions:"
          echo "$STEP_DEF_FILES"

          # Store multi-line values correctly in GitHub environment
          {
            echo "FEATURE_FILES<<EOF"
            echo "$FEATURE_FILES"
            echo "EOF"
          } >> "$GITHUB_ENV"

          {
            echo "STEP_DEF_FILES<<EOF"
            echo "$STEP_DEF_FILES"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Verify automation coverage
        id: check_coverage
        run: |
          python scripts/validate_coverage_DS.py criteria.json "${{ env.FEATURE_FILES }}" "${{ env.STEP_DEF_FILES }}" > coverage_report.txt
          cat coverage_report.txt

